### ISSUE TITLE
运行时报错，请教如何处理

### ISSUE THREAD

**Issue by Asphelzhn** [MercurialJD/Concentration-Detection#2]
运行时报错，请问下如何解决，能否提供一下requirements.txt，谢谢。
Traceback (most recent call last):
  File "concentration_estimation.py", line 178, in <module>
    main()
  File "concentration_estimation.py", line 65, in main
    box_process.start()
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle cv2.dnn_Net objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\xxx\.conda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by MercurialJD** [comment]
我的运行环境：
- Python 3.6.9
- tensorflow 1.14.0
- opencv-python 4.2.0.32

希望能够帮到你

**Comment by Asphelzhn** [comment]
发现是windows的问题，换到Linux就好了。
请问下专注程的判断，只是以检测到人脸姿态框为依据的话效果不太好，有没有其他的判断依据，谢谢

**Comment by MercurialJD** [comment]
鉴于摄像头（尤其是笔记本电脑的）成像效果有限，部分想法难以在这个项目中实现，这里没有更多的办法了。
